# -*- coding: utf-8 -*-
"""2-)California.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yqcg-49XmeoP_dMNrgFmAIVrTVhJoX0G
"""

from sklearn.datasets import fetch_california_housing

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

housing = fetch_california_housing(as_frame=True)

df = housing.data

df.head()

df.isnull().sum()

df['Price'] = housing.target

df["Price"].head()

sns.scatterplot(x="MedInc", y="Price", data=df)

sns.scatterplot(x="HouseAge",y="Price",data = df)

correlation_matrix = df.corr()

# Grafiğin boyutunu ayarlayalım (isteğe bağlı, ama genellikle daha okunabilir yapar)
plt.figure(figsize=(10, 8))

# Isı haritasını çizelim
sns.heatmap(
    data=correlation_matrix, # Görselleştireceğimiz veri
    annot=True,              # Hücrelerin üzerine değerleri yazdır (True = Evet)
    cmap='coolwarm',         # Renk paleti (pozitif/negatif korelasyonları göstermek için iyi bir seçenektir)
    fmt=".2f"
)


plt.show()

from sklearn.model_selection import train_test_split

y = df["Price"]

x = df.drop(columns="Price")

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(x_train,y_train)

model.score(x_test,y_test)

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

model.fit(x_train,y_train)

model.score(x_test,y_test)

